title = "gitleaks config"

[allowlist]
paths = [
    '''docker-compose\.yml''',
    '''docs/authentication\.md''',
    '''docs/configuration\.md''',
    '''examples/.*\.py''',
    '''tests/.*\.py''',
]
